name: agora
services:
  agora:
    image: nonobzh22/agora:2.0.2@sha256:66df9a3efc5df4ec1ecf5845a12d18835d7a18353f5291420b999ed5afa0b71c
    container_name: agora
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 3067
        published: "3067"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
      - type: bind
        source: /DATA/AppData/$AppID/downloads
        target: /downloads
    deploy:
      resources:
        limits:
          memory: 1024M
x-casaos:
  id: space.nolhantirer.agora
  main: agora
  icon: https://raw.githubusercontent.com/NoNoBzH22/TwoBytes-Store/gh-pages/apps/space.nolhantirer.agora/assets/icon.png
  title:
    en_US: Agora
  index: /
  port_map: "3067"
  scheme: http
  version: "2.0.2"
